name: plantyard
description: Yon aplikasyon pou vann plant anliy
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Depandans nesesè yo
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # ✅ PA GEN ANYEN ASÈ ISIT - w ap itilize imaj anliy (network images)
  # ✅ Pa bezwen assets/ oswa fonts/ paske w ap itilize imaj sou entènèt
